lexicon = {
    "Det": ["the", "a", "my", "your", "our"],
    "N": ["cat", "dog", "wankstain", "fun", "sex", "lady", "mink", "Hare Krishna", "shrine maiden", "Bar Mitzvah",
          "ontologist", "war criminal", "paralegal", "shaman", "middle manager", "Freemason",
          "croissant", "teacher", "electrician", "cryptobro", "lifestyle coach",
          "cannibal", "exorcist", "barista", "apple", "editor",
          "therapist", "uncle", "oat milk enthusiast", "obituary writer",
          "friend", "nun", "astrophysicist", "anarchist",
          "intern", "novelist", "exorcist", "emotional support animal"],
    "V": ["has sex", "triangulates", "fucks", "distributes", "thinks", "redpills",
          "litigates", "formally apologizes", "eats", "monetizes", "excommunicates",
          "aggressively networks", "files a complaint", "gaslights", "outsources",
          "radicalizes", "quietly resents", "denounces", "peer reviews", "waterboards",
          "emotionally invests", "over-explains", "audits", "estranges",
          "unironically endorses", "accidentally inspires", "obliterates"],
    "Adj": ["stupid", "languid", "pharisaic", "bdelygmic", "lithe", "funny", "pornographic",
            "post-ironic", "depressed", "moist", "mediocre",
            "incarcerated", "unqualified", "irresponsible", "load-bearing",
            "Scandinavian", "compromised", "peer-reviewed", "lukewarm",
            "ambitious", "offensive", "unavailable",
            "undercooked", "burdened", "radicalised",
            "uninvited", "earnest"],
      "Adv": ["suddenly", "secretly", "offensively", "furiously", "sexily"],
      "P": ["about", "above", "across", "after", "against", "along", "amid", "among", "around", "at", "before", "behind", "below", "beneath",
      "beside", "between", "beyond", "by", "despite", "down", "during",
      "except", "for", "from", "in", "inside", "into", "near", "of",
      "off", "on", "onto", "out of", "outside", "over", "past", "since",
      "through", "throughout", "to", "toward", "under", "underneath",
      "until", "upon", "via", "with", "within", "without"]
}
# Everything after Bar Mitzvah, redpills, and "pornographic" is thanks to Claude. Thank you Claude! 